version: "3"

services:
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -port 8000 -dbPath ./data -sharedDb"
    volumes:
      - "./data:/home/dynamodblocal/data"